#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/book_social_network
#    username: username
#    password: password
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_social_network  # Update URL for MySQL
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver  # Update driver class for MySQL
  jpa:
    hibernate:
      ddl-auto: update  # Keep your existing settings
    show-sql: true  # Keep your existing settings
    properties:
      hibernate:
        format_sql: true  # Keep your existing settings
    database: mysql  # Update database type to MySQL
    database-platform: org.hibernate.dialect.MySQLDialect  # Update dialect for MySQL
  mail:
    host: localhost
    port: 1025
    username: youssef
    password: youssef
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: ture
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  port: 8088